### ISSUE TITLE
Pickle file

### ISSUE THREAD

**Issue by Mugariya** [weiba/MTGCN#2]
Hello,

Can you tell me how you converted the data file from Emogi for CPDB to pickle file because I cannot find the edge indices in there and am confused if what I am taking as edge index is actually the edge index.

Thank you.

**Comment by weiba** [comment]
The Emogi provides a H5 file for CPDB network.  Emogi also provides a Load_data funtion to preprocess the network data and outputs the edge indices. We used the Load_data funtion to preprocess the  H5 file for CPDB network and stored the edge indices in the CPDB_data.pkl file. We also upload the  Load_data.py file to the github.

**Comment by Mugariya** [comment]
Thank you
